### PR TITLE
Proposed pull request

### PR DESCRIPTION
**Pull request by mdewilde**
Could you take a look at the proposed pull request and let me know if interested? As many changes are not backwards compatible, you may have some doubts. I'd like to take the library in a direction as in this pull request, preferably released by you.

### CODE REVIEW

**Comment by DavidePastore** [comment]
Hi @mdewilde. This PR seems interesting. Are you still working on it?

**Comment by mdewilde** [comment]
Hi @DavidePastore, yes I did some more work on it, and I've been using it on the side for the past few days.
Are you open to merging my changes?

**Comment by DavidePastore** [comment]
@mdewilde Yes, if it fixes/improves/adds things.

**Comment by DavidePastore** [comment]
Hi @mdewilde . Is there any reason why you close this PR? Do you think it works correctly? Thanks for your effort on it.

**Pull request closed without merging**
